/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.adapter.ChessAdapter
import edu.austral.dissis.chess.capablancaChess.CapablancaBoardFactory
import edu.austral.dissis.chess.capablancaChess.CapablancaPieceRules
import edu.austral.dissis.chess.capablancaChess.CapablancaSetup
import edu.austral.dissis.chess.classicChess.ClassicChessBoardFactory
import edu.austral.dissis.chess.classicChess.ClassicChessPieceRules
import edu.austral.dissis.chess.classicChess.ClassicChessSetup
import edu.austral.dissis.chess.gui.CachedImageResolver
import edu.austral.dissis.chess.gui.DefaultImageResolver
import edu.austral.dissis.chess.gui.GameView
import edu.austral.dissis.chess.gui.createGameViewFrom
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    private val classicChessSetup = ClassicChessSetup(ClassicChessBoardFactory(), ClassicChessPieceRules())
    private val gameEngine = ChessAdapter(classicChessSetup.createGame())
//    private val capablancaSetup = CapablancaSetup(CapablancaBoardFactory(), CapablancaPieceRules())
//    private val gameEngine = ChessAdapter(capablancaSetup.createCapablancaChess())
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle

        val root = createGameViewFrom(gameEngine, imageResolver)
        primaryStage.scene = Scene(root)

        primaryStage.show()
    }
}